const C='plan-v3';
const FILES=["./", "index.html", "manifest.webmanifest", "icon-192.png", "icon-512.png", "icon-180.png", "demo/Band_Pull_Apart_0.jpg", "demo/Band_Pull_Apart_1.jpg", "demo/Barbell_Bench_Press_-_Medium_Grip_0.jpg", "demo/Barbell_Bench_Press_-_Medium_Grip_1.jpg", "demo/Barbell_Deadlift_0.jpg", "demo/Barbell_Deadlift_1.jpg", "demo/Barbell_Squat_0.jpg", "demo/Barbell_Squat_1.jpg", "demo/Bicycling_Stationary_0.jpg", "demo/Bicycling_Stationary_1.jpg", "demo/Butt_Lift_Bridge_0.jpg", "demo/Butt_Lift_Bridge_1.jpg", "demo/Close-Grip_Front_Lat_Pulldown_0.jpg", "demo/Close-Grip_Front_Lat_Pulldown_1.jpg", "demo/Dead_Bug_0.jpg", "demo/Dead_Bug_1.jpg", "demo/Dumbbell_Bicep_Curl_0.jpg", "demo/Dumbbell_Bicep_Curl_1.jpg", "demo/Dumbbell_Lunges_0.jpg", "demo/Dumbbell_Lunges_1.jpg", "demo/Dumbbell_One-Arm_Triceps_Extension_0.jpg", "demo/Dumbbell_One-Arm_Triceps_Extension_1.jpg", "demo/Dumbbell_Step_Ups_0.jpg", "demo/Dumbbell_Step_Ups_1.jpg", "demo/External_Rotation_with_Band_0.jpg", "demo/External_Rotation_with_Band_1.jpg", "demo/Face_Pull_0.jpg", "demo/Face_Pull_1.jpg", "demo/Flat_Bench_Lying_Leg_Raise_0.jpg", "demo/Flat_Bench_Lying_Leg_Raise_1.jpg", "demo/Goblet_Squat_0.jpg", "demo/Goblet_Squat_1.jpg", "demo/Hammer_Curls_0.jpg", "demo/Hammer_Curls_1.jpg", "demo/Incline_Dumbbell_Press_0.jpg", "demo/Incline_Dumbbell_Press_1.jpg", "demo/Internal_Rotation_with_Band_0.jpg", "demo/Internal_Rotation_with_Band_1.jpg", "demo/Lying_Leg_Curls_0.jpg", "demo/Lying_Leg_Curls_1.jpg", "demo/One-Arm_Dumbbell_Row_0.jpg", "demo/One-Arm_Dumbbell_Row_1.jpg", "demo/Plank_0.jpg", "demo/Plank_1.jpg", "demo/Rocking_Standing_Calf_Raise_0.jpg", "demo/Rocking_Standing_Calf_Raise_1.jpg", "demo/Seated_Cable_Rows_0.jpg", "demo/Seated_Cable_Rows_1.jpg", "demo/Seated_Dumbbell_Press_0.jpg", "demo/Seated_Dumbbell_Press_1.jpg", "demo/Side_Lateral_Raise_0.jpg", "demo/Side_Lateral_Raise_1.jpg", "demo/Stairmaster_0.jpg", "demo/Stairmaster_1.jpg", "demo/Stiff-Legged_Dumbbell_Deadlift_0.jpg", "demo/Stiff-Legged_Dumbbell_Deadlift_1.jpg", "demo/Triceps_Pushdown_-_Rope_Attachment_0.jpg", "demo/Triceps_Pushdown_-_Rope_Attachment_1.jpg", "demo/Walking_Treadmill_0.jpg", "demo/Walking_Treadmill_1.jpg", "demo/Wide-Grip_Lat_Pulldown_0.jpg", "demo/Wide-Grip_Lat_Pulldown_1.jpg"];
self.addEventListener('install',e=>{e.waitUntil(caches.open(C).then(c=>c.addAll(FILES)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==C).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;
  const u=new URL(e.request.url);
  if(u.pathname.endsWith('/')||u.pathname.endsWith('index.html')){ // 页面：先网络后缓存，保证能拿到更新
    e.respondWith(fetch(e.request).then(r=>{const cp=r.clone();caches.open(C).then(c=>c.put(e.request,cp));return r}).catch(()=>caches.match(e.request)));return;}
  e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)));});
